io:
  netty:
    resolver:
      dns:
        use-system-resolver: true
#keycloak:
#  url: http://localhost:8080/realms/myrealm/protocol/openid-connect/token
#  client-id: amo-client
#  client-secret: LM8vaTxgVjUhokBSpu4RSPuunlsho9be

keycloak:
  realm: amo-realm
  auth-server-url: http://localhost:8090
  resource: amo-client
  credentials:
    secret: LM8vaTxgVjUhokBSpu4RSPuunlsho9be
  use-resource-role-mappings: true

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
          - id: user_service
            uri: ${USERS_ROUTE_URI:http://localhost:8081}
            predicates:
              - Path=/droits/**
            filters:
              - PrefixPath=/api
              #- AddRequestHeader=Authorization, Bearer ${token}


  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
      gateway:
        enabled: true
